# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod tidy
builds:
- id: localpod
  binary: localpod
  env:
  - CGO_ENABLED=0
  main: ./main.go
  goos:
  - darwin
  - linux
  goarch:
  - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
  files:
  - README.md
  - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
nfpms:
- id: deb
  package_name: localpod
  formats:
  - deb
- id: apk
  package_name: localpod
  formats:
  - apk
publishers:
- name: deb
  ids:
  - deb
  cmd: hack/publish_deb {{ abs .ArtifactPath }} {{ .ArtifactName }} {{ .Arch }}
  env:
  - ARTIFACTORY_USERNAME={{ .Env.ARTIFACTORY_USERNAME }}
  - ARTIFACTORY_SECRET={{ .Env.ARTIFACTORY_SECRET }}
- name: apk
  ids:
  - apk
  cmd: hack/publish_apk {{ abs .ArtifactPath }} {{ .ArtifactName }} {{ .Arch }}
  env:
  - ARTIFACTORY_USERNAME={{ .Env.ARTIFACTORY_USERNAME }}
  - ARTIFACTORY_SECRET={{ .Env.ARTIFACTORY_SECRET }}
brews:
- name: localpod
  tap:
    owner: bottlerocketlabs
    name: homebrew-apps
    token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
  folder: Formula
  homepage:  https://github.com/bottlerocketlabs/localpod
  description: A tool help local development environments
  license: MIT
  test: |
    system "#{bin}/localpod -help"
  dependencies:
  - name: go
  install: |-
    bin.install "localpod"
